### ISSUE TITLE
Dateien Link im Editor anklickbar und nicht mehr einstellbar

### ISSUE THREAD

**Issue by jswebschmiede** [aeberhard/tinymce#3]
Hallo,
folgender Fehler tritt seit neusten bei mir auf. 

Wenn ich eine Datei einbaue über den Datei/Link einfügen Button. Passiert folgendes. 

Will ich die Datei erneut ändern, öffnet sich der Link wenn man auf den Text klickt. Des weiteren ist die Datei nicht mehr änderbar, da der Button nicht mehr anklickbar ist. Nur der Link Funktion wird gezeigt, da kann ich aber nur Artikel als Link wählen.

**Comment by aeberhard** [comment]
Hallo Jörg,
habe das Addon gerade upgedated auf die aktuelle TinyMCE-Version.
Kann den Fehler nicht nachvovllziehen!
LG
Andreas
