### ISSUE TITLE
jQuery 1.8.3 compat

### ISSUE THREAD

**Issue by jdlx** [aeberhard/tinymce#4]
Da der rex core in 4.4.2 ein update auf [jQuery 1.8.3](https://github.com/redaxo/redaxo4/pull/77) erfahren soll, wärs wichtig Tiny dahingehend mal anzuklopfen..

cheers,
Jan

**Comment by aeberhard** [comment]
Ist mit Update auf TinyMCE 3.5.8 erledigt, getestet unter 4.4.1 mit der jQuery-Version aus 4.4.x

lg
andreas
