### ISSUE TITLE
medienpool in redaxo ist optisch durcheinander

### ISSUE THREAD

**Issue by dergel** [aeberhard/tinymce#5]
Der AGK Skin greift nicht mehr und es erscheint das grüne Layout. Eventuell wird etwas in der Config im Header überschrieben ?

**Comment by aeberhard** [comment]
Hallo Jan, kann das hier nicht nachvollziehen sieht alles ok aus (4.5.0), hast Du da mehr Hinweise ?!

**Comment by dergel** [comment]
![Bildschirmfoto 2013-02-14 um 12 57 52](https://f.cloud.github.com/assets/322951/156604/1c7559b2-769e-11e2-9caf-7034dd402ca9.png)
![Bildschirmfoto 2013-02-14 um 12 58 07](https://f.cloud.github.com/assets/322951/156605/1d0b8b12-769e-11e2-9783-aa1a7d74507a.png)

schau mal..

**Comment by dergel** [comment]
mein Fehler - falsche Testumgebung.. sorry
