### ISSUE TITLE
call tinymce4_init.de.js macht backend langsam

### ISSUE THREAD

**Issue by darwin26** [aeberhard/tinymce#9]
Hi,
mir ist aufgefallen das der call tinymce4_init.de.js das Backend träge erscheien lässt.
**index.php?tinymce4_call=/asset_js/tinymce4_init.de.js**
![00](https://cloud.githubusercontent.com/assets/189407/20621028/ef8555ac-b2fc-11e6-8d5b-e01c00dbaab1.png)

Fühlt sich an als würde der TinyMCE bei jedem Seitenaufruf des Backends neu geladen...
getestet unter OSX (FF,Chrome, Safari // PHP Version 7.0.10) lokal und aufm server.

Danke. Gruß Chris

**Comment by aeberhard** [comment]
Hi Chris,
schau mal hier :)
https://github.com/akuehnis/redaxo5_addon_tinymce4/issues/11

**Comment by darwin26** [comment]
ah. danke. closed
